# This is a basic workflow to help you get started with Actions
name: ipnoticias

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/3 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: config
        run: |
          git pull
          git config --global user.email "elselloweb@gmail.com"
          git config --global user.name "ElSelloTV"
      
      - name: Main (ipnoticias)
        run: |
          pwd
          chmod +x ipnoticias.sh
          ./ipnoticias.sh
        
      - name: Main (c26)  # Agrega esta tarea para el nuevo canal "c26"
        run: |
          pwd
          chmod +x c26.sh  # Asegúrate de tener un script específico para c26.sh
          ./c26.sh

      - name: git add
        run: |
          git add -A
          
      - name: commit & push
        run: |
          git commit -m "Link updated"
          git push
